server:
  port: 8080


spring:
  config:
    import: secrets.yml
  servlet: # max file size
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher # Spring boot 2.6 이후부터  spring.mvc.pathmatch.matching-strategy 값이 ant_path_matcher에서 path_pattern_parser로 변경
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cloneproject.coi5bl8jchez.ap-northeast-2.rds.amazonaws.com:3306/cloneproject?serverTimezone=Asia/Seoul
    username: ${RDS.username}
    password: ${RDS.password}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1

  jpa:
    hibernate:
      ddl-auto: update #create update none
      use-new-id-generator-mappings: false
    generate-ddl: true # ddl-auto 속성을 사용할지 말지
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  output: # output 색깔이 이뻐짐
    ansi:
      enabled: always

jwt:
  secret: ${jwt.secret}